name: analytics
description: Simple analytics library for Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

resolution: workspace

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: 1.19.1

  # Firebase
  firebase_analytics: ^11.5.0

  # Local Packages
  logger:
    path: ../logger

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: 5.4.6
  build_runner: ^2.5.3

flutter:
  uses-material-design: true