include: package:sizzle_lints/lints.yaml

formatter:
  page_width: 100
  trailing_commas: preserve

analyzer:
  exclude:
    - "lib/src/core/localization/generated/**"
    - "**/*.*.dart"
    - "**/generated/**"
