include: package:sizzle_lints/lints.yaml

analyzer:
  exclude: 
    - "lib/src/core/localization/generated/**"
    - "**/*.*.dart"
    - "**/generated/**"

dart_code_metrics:
  extends:
    - package:sizzle_lints/dcm.yaml