name: settings
description: "Settings domain module"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  common:
    path: '../../core/common'

dev_dependencies:
  flutter_test:
    sdk: flutter
