name: home
description: "Home feature"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  settings:
    path: ../settings
  ui_library:
    path: ../../core/ui_library

dev_dependencies:
  flutter_test:
    sdk: flutter
