name: settings_presentation
description: Settings presentation module
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  settings_domain:
    path: ../settings_domain
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
