name: settings_impl
description: Settings implementation module
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  settings_domain:
    path: ../settings_domain